[Simulation]
# min and max thrust (N)
Tmin = 0, 0, 0
Tmax = 1, 1, 1

# wet and dry spacecraft mass (kg). Mothership default 12, 11
m_wet = 200, 12, 12
m_dry = 180, 11, 11

# surface area (m^2). Mothership default 3.14
S = 3.14, 0.36, 0.36

# number of states and number of controls
numstates = 7
m = 4

# specific impulse of thrusters (s)
isp = 225, 75, 75

# Designations (no spaces!!!!!)
designations = mothership,daughtership1,daughtership2

# reference trajectory location
folder = apophis-reference-trajectories

# ESTIMATED initial position and velocity (km, km/s)
dxhat_0 = 0.0, 0.002, -0.002
dyhat_0 = 0.0, 0.002, -0.002
dzhat_0 = 0.0, 0.002, -0.002
dvxhat_0 = 0.0, 0.000001, -0.000001
dvyhat_0 = 0.0, 0.000001, -0.000001
dvzhat_0 = 0.0, 0.000001, -0.000001

# number of timesteps in MPC prediction horizon
horizon = 10, 10, 10

# Covariance P diagonal entries (km^2, km^2/s^2, kg^2)
Px = 0.000004, 0.000004, 0.000004
Py = 0.000004, 0.000004, 0.000004
Pz = 0.000004, 0.000004, 0.000004
Pvx = 1e-12, 1e-12, 1e-12
Pvy = 1e-12, 1e-12, 1e-12
Pvz = 1e-12, 1e-12, 1e-12
Pq = 1e-16, 1e-16, 1e-16

# Process noise spectral density matrix Q diagonal entries (km^2/s^2/Hz = km^2/s^3) in RTN frame
# q_[] = deltat * ||max(a_unmodeled,[])||^2
# from Bennu accel mag chart, n is thermal re-radiation, r is oblateness, t is some other stochastic accels
a_r = 0.000000000005, 0.000000000005, 0.000000000005
a_t = 0.000000000001, 0.000000000001, 0.000000000001
a_n = 0.00000000001, 0.00000000001, 0.00000000001

# measurement noise 1 sigma variance (pixels^2, pixels^2, km^2, km^2/s^2, km^2, km^2/s^2) (1e-12 for km^2/s^2) 0.01, 0.01, 2e-10, 0.01, 0.01, 2e-10
v = 0.01, 0.01, 0.01, 0.01, 2e-10, 0.01, 0.01, 2e-10
v_start = 0, 2, 5
v_end = 2, 5, 8

# camera field of view, always pointed to asteroid CoM (degrees)
fov = 24

# focal length (mm)
f = 12

# pixel size/pitch (px/mm)
pixel_pitch = 0.00325

# camera size (pixels)
width = 1024
height = 1024

# generate (0) or use existing reference trajectories (1)
ref_traj_setting = 0, 0, 0

# generate (0) or use existing initial conditions (1) if generating reference trajectories
ics_gen_setting = 0, 0, 0

# initial states (if generating reference trajectories and want prescribed initial conditions (0, 1 above), km, km/s)
x_0 = 0.076682698079531611, -0.033925557289467306, 0.030428423387198960
y_0 = 1.1639106787116784, -0.46863942173963041, 0.48120918827270348
z_0 = -3.1132672756505015, 1.2804714780349655, -1.2758890568066648
vx_0 = -0.000028941236213087830, 0.000039626490887801602, -0.000039628879879855215
vy_0 = -0.0000068574735702273788, 0.0000093892884168185679, -0.0000093898544759097039
vz_0 = -0.0000032765509327547089, 0.0000044862705492002076, -0.0000044865410163662899

# initial radius, true anomaly if generating initial conditions (km, rad)
r_0 = 2, 1, 1
ta_0 = 3.14159265359, 4.71238898038, 1.57079632679
t_0 = 0, 0, 0

# number of steps and time step (if generating reference trajectories, unitless, seconds) 4320, 4500, 8640, 8800
N = 4320
N_ref = 4500
dt = 600

# multiplier to apply to dt for the MPC horizon to step in a single step: mult = 4 -> 1 step in MPC = 4*dt
dt_MPC_multiplier = 8

# ephemeris BSpline interpolation order k > 0
k = 7, 7, 7

# number of range measurements per batch
N_batch = 8

# deltaV minimum as a multiple of gates sigma_1
gates_1_factor = 3

# reflectivity coefficient (C_R) [1, 2]   0.857
C_R = 1.2, 1.2, 1.2

# daughtership measurement model "image_range"
model = image_range

# orbit classification "terminator", "halo"
orbit = halo,halo,halo

[Asteroid]
# asteroid names: bennu, kleopatra, geographos, bacchus, toutatis, castalia, golevka, itokawa, apophis
asteroid = apophis

# number of features on asteroid
fnum = 600

[Gates]
# standard deviations for the Gates model: fixed and proportional-magnitude errors (1 and 2) and fixed and proportional-pointing errors (3 and 4) based on Cassini Maneuver Performance Assessment RCS thrusters
# units: km/s, %, mm/s, mrad
s1 = 0.00000085, 0.00000085, 0.00000085
s2 = 0, 0, 0
s3 = 0, 0, 0
s4 = 4.3, 4.3, 4.3
