[Simulation]
# min and max thrust (N)
Tmin = 0, 0, 0
Tmax = 80, 80, 80

# wet and dry spacecraft mass (kg)
m_wet = 200, 14, 14
m_dry = 180, 13, 13

# surface area (m^2)
S = 3.2, 0.06, 0.06

# number of states and number of controls
numstates = 7
m = 4

# specific impulse of thrusters (s)
isp = 225, 225, 225

# Designations (no spaces!!!!!)
designations = mothership,daughtership1,daughtership2

# reference trajectory location
folder = apophis-reference-trajectories

# ESTIMATED initial position and velocity (km, km/s)
dxhat_0 = 0.02, 0.02, 0.02
dyhat_0 = 0.02, 0.02, 0.02
dzhat_0 = 0.02, 0.02, 0.02
dvxhat_0 = 0.00001, 0.00001, 0.00001
dvyhat_0 = 0.00001, 0.00001, 0.00001
dvzhat_0 = 0.00001, 0.00001, 0.00001

# number of timesteps in MPC prediction horizon
horizon = 5, 5, 5

# Covariance P diagonal entries (km^2, km^2/s^2, kg^2)
Px = 0.0004, 0.0004, 0.0004
Py = 0.0004, 0.0004, 0.0004
Pz = 0.0004, 0.0004, 0.0004
Pvx = 1e-10, 1e-10, 1e-10
Pvy = 1e-10, 1e-10, 1e-10
Pvz = 1e-10, 1e-10, 1e-10
Pq = 0.0, 0.0, 0.0

# Process noise matrix Q diagonal entries (km^2, km^2/s^2, kg^2)
Qx = 1e-12, 1e-12, 1e-12
Qy = 1e-12, 1e-12, 1e-12
Qz = 1e-12, 1e-12, 1e-12
Qvx = 1e-15, 1e-15, 1e-15
Qvy = 1e-15, 1e-15, 1e-15
Qvz = 1e-15, 1e-15, 1e-15
Qq = 0.0, 0.0, 0.0

# measurement noise 1 sigma variance (pixels^2, pixels^2, km^2, km^2)
v = 0.0625, 0.0625, 5e-10, 5e-10
v_start = 0, 2, 3
v_end = 2, 3, 4

# camera field of view, always pointed to asteroid CoM (degrees)
fov = 24

# focal length (mm)
f = 12

# camera size (pixels)
width = 512
height = 512

# select which cost function to use: "fixed", "terminal_free", "terminal_fuel_weighted_free" "progress_free", "no_fuel_free", "progress_ones_free"
cost_function_to_use = terminal_fuel_weighted_free

# Monte Carlo? 1 means you are doing Monte Carlo sims, so you want the initial conditions varied. Sigmas are 1 sigma values (km, km/s) to vary the ICs around with a mean value of the reference trajectory ICs
monte_carlo_bool = 0
monte_carlo_pos_x_sigma = 4.444e-5, 4.444e-5, 4.444e-5
monte_carlo_pos_y_sigma = 4.444e-5, 4.444e-5, 4.444e-5
monte_carlo_pos_z_sigma = 4.444e-5, 4.444e-5, 4.444e-5
monte_carlo_pos_vx_sigma = 1.111e-9, 1.111e-9, 1.111e-9
monte_carlo_pos_vy_sigma = 1.111e-9, 1.111e-9, 1.111e-9
monte_carlo_pos_vz_sigma = 1.111e-9, 1.111e-9, 1.111e-9

# generate (0) or use existing reference trajectories (1)
ref_traj_setting = 0, 0, 0

# initial states (if generating reference trajectories, km, km/s)
x_0 = 0, 1, -1
y_0 = 0, 0, 0
z_0 = 3, 0, 0
vx_0 = 0.00003684, 0, 0
vy_0 = 0, 0.0000638064416811, -0.0000638064416811
vz_0 = 0, 0, 0

# number of steps and time step (if generating reference trajectories, unitless, seconds)
N = 1000
dt = 600

# time between daughtership batches and number of range measurements per batches
t_batch = 3600
N_batch = 5

[Asteroid]
# asteroid names: bennu, kleopatra, geographos, bacchus, toutatis, castalia, golevka, itokawa, apophis
asteroid = golevka

# number of features on asteroid
fnum = 600